### ISSUE TITLE
请问一下版本号的规则是怎么定的

### ISSUE THREAD

**Issue by kengkenghaojie** [vaenow/cordova-plugin-app-update#103]
versionName	versionCode
0.0.1                 	18
0.3.4	                      3048
3.2.4	                    302048
12.234.221	   1436218
这存在什么规律吗？求解答

**Comment by vaenow** [comment]
Cordova 官方的版本生成规则 ：
https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#setting-the-version-code

参考：#3
