### ISSUE TITLE
code: 405, msg: "network error"

### ISSUE THREAD

**Issue by SmallProgramIndustry** [vaenow/cordova-plugin-app-update#104]
新的项目没有这样的问题，我在工作中的项目，重装了插件很多遍，装插件也没报错，这是为什么呢？
The new project does not have such a problem. I work in the project, re installed many times plug-ins, plug-ins did not report wrong, why?

**Comment by SmallProgramIndustry** [comment]
这个插件很好，很多操作都省去了，程序员体验非常好，但是我还是我想搞清楚为什么出现那种情况

**Comment by vaenow** [comment]
“network error” 这个报错一般是网络请求失败。
有几种可能：
1. 目前不支持https    => #101 
2. 更新的资源出现 404
3. 网络可能真的不稳定

**Comment by SmallProgramIndustry** [comment]
那好的，谢谢
