### ISSUE TITLE
关于强制更新

### ISSUE THREAD

**Issue by zhaopeiym** [vaenow/cordova-plugin-app-update#105]
## 关于更新可否提供**两个方式**
- 1、可以选择更新或者取消（非强制更新）
- 2、只能点击更新，否则只能退出程序。（强制更新）

## 现状：
- 1、没有取消按钮（建议添加取消按钮）
- 2、安卓版本的更新按返回键，可以不更新继续使用。（能不能处理成不让返回）

**Comment by vaenow** [comment]
谢谢你的建议，这有个相似的MR #96
