### ISSUE TITLE
New update doesn't install after download in android 8

### ISSUE THREAD

**Issue by nasserghiasi** [vaenow/cordova-plugin-app-update#107]
In Android 8 all apps need permission to install apk file, the plugin doesn't compatible with android 8 new feature.

**Comment by ZeroQool007** [comment]
I am using Android 8.1 and I've got the same issue. I need a fix, please. thanks

**Comment by fxp528** [comment]
You can add <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"/>. It works to me

**Comment by vaenow** [comment]
Fixed #118 Thank you 🙂

**Comment by sealover06** [comment]
Hello Vaenow and team.  Let me start: this plugin is awesome.  Works like a charm, except when run as well with the kiosk plugin. 
I opened the generated apk, and could see  in the AndroidManifest.xml
<uses-permission
        android:name="android.permission.INTERNET" />

    <uses-permission
        android:name="android.permission.READ_EXTERNAL_STORAGE" />

    <uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    <uses-permission
        android:name="android.permission.REQUEST_INSTALL_PACKAGES" />

    <uses-permission
        android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS" />

    <uses-permission
        android:name="android.permission.REORDER_TASKS" />

    <uses-permission
        android:name="android.permission.SYSTEM_ALERT_WINDOW" />

so seems that I have the         android:name="android.permission.REQUEST_INSTALL_PACKAGES" />  mentioned above as a way to fix this issue. 

My Tablet runs android 6.0.1

Thanks for help.
