### ISSUE TITLE
Make compatible with latest cordova and cordova-android versions

### ISSUE THREAD

**Issue by genox** [vaenow/cordova-plugin-app-update#108]
Hi,

Getting this error on app deployed to device:

`AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.vaenow.appupdate.android.GenericFileProvider" on path: DexPathList[[zip file "/xxxxxxxxx/base.apk"],nativeLibraryDirectories=[/xxxxxxxxxx/lib/arm, /system/lib, /vendor/lib]]`

According to other issues for this project, this is most certainly a compatibility issue, seems like cordova-android 6.3.0 is the only compatible version.

Can I kindly ask you to update the plugin to support cordova-android 7.1.0?

**Comment by kashban** [comment]
I second that. Cordova Android 7.0 is out quite some time now.
