### ISSUE TITLE
The download has finished but it doesn't install

### ISSUE THREAD

**Issue by lalogrosz** [vaenow/cordova-plugin-app-update#109]
After downloading, It shows me 2 options. Download Again and Install Manually, the Install Manually option doesn't do anything.
In a genymotion emulator with Android 6 It works perfectly but in others devices it behaves different.
It starts to fail after I change the minor 1.0.14 (10014) to 1.1.0 (10100).
Any idea? 

![whatsapp image 2018-07-06 at 11 19 02](https://user-images.githubusercontent.com/1898486/42405717-2f5cebd8-8171-11e8-9c57-3ddd690e7ad7.jpeg)

**Comment by arthursp** [comment]
linked to #107

**Comment by carlo318** [comment]
I am facing this issue several times on Android 6.0.
I think that, in my case, there is an issue between this plugin and the cordova-plugin-kiosk, which inhibit the autorestart (and update) of the app.
I still haven't solve this issue.
