### ISSUE TITLE
安装插件后闪退

### ISSUE THREAD

**Issue by hearsay316** [vaenow/cordova-plugin-app-update#110]
当我按照官网安装好插件，打包后的apk安装在手机上 ，闪退。

**Comment by yexiaodong** [comment]
你解决了吗？我也遇到同样的问题。安装插件后，app无法打开；

**Comment by hearsay316** [comment]
> ？你解决了吗我也遇到同样的问题安装插件后，应用程序无法打开。

换了一种方式

**Comment by jdzhou** [comment]
> > ？你解决了吗我也遇到同样的问题安装插件后，应用程序无法打开。
> 
> 换了一种方式

换了什么方式，提供一下思路 谢谢

**Comment by vaenow** [comment]
Fixed #95
