### ISSUE TITLE
Application crash when auto update function hit

### ISSUE THREAD

**Issue by Hardik21** [vaenow/cordova-plugin-app-update#114]
This is my code:

` ionViewDidLoad() {
      const updateUrl = 'http://lifelinetech.org/update.xml';
     this.appUpdate.checkAppUpdate(updateUrl).then(() => {
         alert("call for change version");
     });
  }`

**Comment by ZeroQool007** [comment]
You've to change your xml. Dont use 0.0.4, use 4

**Comment by vaydich** [comment]
Hi!

I have the same behaviour.

My code:

```
const updateUrl = 'http://192.168.0.4:8102/update.xml';
    this._appUpdate.checkAppUpdate(updateUrl).then(() => {
      alert('Update available');
      console.warn('Update available');
    });
```

```
<update>
<version>2</version>
<name>app-debug</name>
<url>http://192.168.0.4:8102/app-debug.apk</url>
</update>
```

but when i start apk it crashes
