### ISSUE TITLE
hot to work on Android 6.x and later

### ISSUE THREAD

**Issue by yelban** [vaenow/cordova-plugin-app-update#13]
thank you build the awesome  plugin
it work fine on android 4.x, but not for 6.x/ 7.x ( emulator and real device )
is there any walk run for android 6.x+ ? 

![screenshot_android7](https://cloud.githubusercontent.com/assets/981381/18983477/8fa6dbaa-871f-11e6-84bd-3372ee846ca3.png)

**Comment by vaenow** [comment]
- Could you show me more details about android 6.x.  

- Maybe you can check out the `versionCode` and paste it below comments

```js
var versionCode = AppVersion.build
console.log(versionCode)  // 302048
```

**Comment by yelban** [comment]
sure, all the version code is "30203"
Sony Z3 (android 6.0.1) ,  android avd ( 7.0 and 4.1.2 )

android 4.1.2 display two blue line ( one for progress bar)
android 6.0.x display only one gray line

**Comment by chingfeng** [comment]
Android added new permission model for Android M.

Please check this page that will help you handling the permissions in M.
> http://www.cnblogs.com/zzw1994/p/5021118.html

or use Android's DownloadManager to download apk file, and install it after _"DownloadManager.ACTION_DOWNLOAD_COMPLETE"_ received.

**Comment by vaenow** [comment]
@chingfeng Would you please send me a `pull request`, thanks in advance.

**Comment by yelban** [comment]
hope this link will help :)

how to use Android 7.0 FileProvider 
http://www.techug.com/android7-0-rom-mod

**Comment by mzszhznn** [comment]
感谢，很好的插件。
在高版本遇到同样的问题。
能不能在下一个版本得到兼容处理呢？

**Comment by vaenow** [comment]
看来已经有很多同学遇到了这个麻烦，我会尽快处理。 

I'll handle this as soon as possible

**Comment by vaenow** [comment]
Thanks @chingfeng 's pull request #16 

👍
