### ISSUE TITLE
卡在「正在更新」

### ISSUE THREAD

**Issue by donkeyban** [vaenow/cordova-plugin-app-update#14]
您好，設定完成之後如下兩張圖片
最後都會卡在「正在更新」
請問我可以使用什麼方式知道是發生什麼錯誤？
感謝您
https://drive.google.com/open?id=0Bx0cPcflw0seNFB6VUpiQ1NVVzg
https://drive.google.com/open?id=0Bx0cPcflw0sebEIyRjloaFplWWM

**Comment by vaenow** [comment]
请留下你的设备型号，系统版本，以便排查问题。

**Comment by donkeyban** [comment]
SONY Xperia TX
Android 5.1.1
感謝您

**Comment by vaenow** [comment]
更新的version.xml内容是什么呢?

可能只是下载路径出错了

**Comment by donkeyban** [comment]
不好意思...經過您的提醒
剛剛去詢問我們網管，才知道
上星期有變更對外服務的Port...
程式修改後，正常了～
