### ISSUE TITLE
你好！使用cordova-plugin-app-update

### ISSUE THREAD

**Issue by GK303** [vaenow/cordova-plugin-app-update#18]
请问在添加cordova-plugin-app-update这个插件后，然后复制你demo里面的内容到新建的项目中，我还需要有什么具体的操作吗？1638722289@qq.com，这是我的联系方式，希望可以得到您的帮助

**Comment by vaenow** [comment]
这个问题有点不太好回答。
插件使用方式可以参考 [https://github.com/vaenow/cordova-plugin-app-update-demo](https://github.com/vaenow/cordova-plugin-app-update-demo)
