### ISSUE TITLE
Support Authentication

### ISSUE THREAD

**Issue by kaspro** [vaenow/cordova-plugin-app-update#20]
Hi,
first of all thanks for this great, easy Plugin!
Is it somehow possible to add authentication to this (Basic / Basic Header)? I tried with https://user:pass@url/ but it won't work.
Since this is used for updating apps "off" the market, I'd find this addition quite handy... :)

Thanks in advance,
Cheers Chris

**Comment by vaenow** [comment]
Unfortunately, I'm not quite understand how to add authentication to this plugin. 
Maybe you can try it yourself 👍
