### ISSUE TITLE
support for ios

### ISSUE THREAD

**Issue by mnewmedia** [vaenow/cordova-plugin-app-update#23]
support for ios

**Comment by lahdekorpi** [comment]
iOS is locked down. You can't do that.

**Comment by mnewmedia** [comment]
Yep, alot of stuff is locked down, but it's possible. I use currently:
https://github.com/nordnet/cordova-hot-code-push

**Comment by lahdekorpi** [comment]
It is not.

The plugin you linked updates the HTML part of the app, meaning what is running inside the Webview.
This plugin updates the whole app. APK.

**Comment by mnewmedia** [comment]
Oh, didn't know this plugin does update the whole App.
