### ISSUE TITLE
has no exported member 'AppUpdate'.

### ISSUE THREAD

**Issue by hrobar** [vaenow/cordova-plugin-app-update#24]
Hello, 
sry for my english.
I install plugin http://ionicframework.com/docs/v2/native/appupdate/ to ionic2 app
and i add row in app.components.ts
`import { AppUpdate } from 'ionic-native';`

and start `ionic serve`

and show me  error `Module '"d:/androidapp/testAppUpdate/node_modules/ionic-native/dist/es5/index"' has no exported member 'AppUpdate'.`

**Comment by vaenow** [comment]
@hrobar `AppUpdate` is not served in `ionic-native`

try `window.AppUpdate` in common use, 
or 
try `$window.AppUpdate` in Angular1.x project

**Comment by hrobar** [comment]
thx, but i compiled ionic 2 app and show me this error
`
C:\xampp\htdocs\androidapp\testAppUpdate\platforms\android\src\com\vaenow\appupdate\android\CheckAppUpdate.java:6: error: package android.support.v4.app does not exist
import android.support.v4.app.ActivityCompat;

                             ^

C:\xampp\htdocs\androidapp\testAppUpdate\platforms\android\src\com\vaenow\appupdate\android\CheckAppUpdate.java:52: error: cannot find symbol


        int permission = ActivityCompat.checkSelfPermission(activity,

                         ^
  symbol:   variable ActivityCompat

  location: class CheckAppUpdate

C:\xampp\htdocs\androidapp\testAppUpdate\platforms\android\src\com\vaenow\appupdate\android\CheckAppUpdate.java:57: error: cannot find symbol
            ActivityCompat.requestPermissions(activity, PERMISSIONS_STORAGE,
            ^
  symbol:   variable ActivityCompat
  location: class CheckAppUpdate

Note: C:\xampp\htdocs\androidapp\testAppUpdate\platforms\android\src\org\apache\cordova\splashscreen\SplashScreen.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

:compileDebugJavaWithJavac FAILED

BUILD FAILED

Total time: 18.166 secs

3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\xampp\htdocs\androidapp\testAppUpdate\platforms\android\src\com\vaenow\appupdate\android\CheckAppUpdate.java:6: error: package android.support.v4.app does not exist
import android.support.v4.app.ActivityCompat;
                             ^
C:\xampp\htdocs\androidapp\testAppUpdate\platforms\android\src\com\vaenow\appupdate\android\CheckAppUpdate.java:52: error: cannot find symbol
        int permission = ActivityCompat.checkSelfPermission(activity,
                         ^
  symbol:   variable ActivityCompat
  location: class CheckAppUpdate
C:\xampp\htdocs\androidapp\testAppUpdate\platforms\android\src\com\vaenow\appupdate\android\CheckAppUpdate.java:57: error: cannot find symbol
            ActivityCompat.requestPermissions(activity, PERMISSIONS_STORAGE,
            ^
  symbol:   variable ActivityCompat
  location: class CheckAppUpdate
Note: C:\xampp\htdocs\androidapp\testAppUpdate\platforms\android\src\org\apache\cordova\splashscreen\SplashScreen.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.`

**Comment by vaenow** [comment]
`package android.support.v4.app does not exist`

This link [#17](https://github.com/vaenow/cordova-plugin-app-update/issues/17#issuecomment-264868781) may help you.

**Comment by dayaki** [comment]
@hrobar you need to update your ionic native to @2.6.0, appUpdate was added with the 2.6.0 update
