### ISSUE TITLE
no update

### ISSUE THREAD

**Issue by hrobar** [vaenow/cordova-plugin-app-update#26]
I call in ionic 2
`AppUpdate.checkAppUpdate('https://localhost/update-mobil/update.xml')`

and return 

`{"__zone_symbol__state":null,"__zone_symbol__value":"[]"}`

what wrong?
thx

**Comment by hrobar** [comment]
sry, my bad

**Comment by dayaki** [comment]
@hrobar how were you able to install these in ionic and not get error?
