### ISSUE TITLE
VersionCode generate rule 版本规则

### ISSUE THREAD

**Issue by wzcrystal** [vaenow/cordova-plugin-app-update#3]
when get the android:versionCode in AndroidManifest.xml , is always add "8" in the end, even though update to this version , it is always reminder to update , I do not know why , maybe is the cordova own problem, do you have some solutions?

**Comment by vaenow** [comment]
If you always got "8" in the end, you can try this rule in your `version.xml` below:


versionName | versionCode
------- | ----------------
0.0.1  | 18
0.3.4  | 3048 
3.2.4   | 302048
12.234.221  | 1436218

```xml
<update>
    <version>302048</version>
    <name>name</name>
    <url>http://192.168.0.1/android.apk</url>
</update>
```

Note the end of `8` number

**Comment by wzcrystal** [comment]
yes,I also take this way,but I want to know why does this happen, do you know?

**Comment by vaenow** [comment]
Cheers! :beers:   I got the answer when I just almost say sorry to you.


In `platforms/android/build.grade`
```gradle
if (Boolean.valueOf(cdvBuildMultipleApks)) {
        productFlavors {
            armv7 {
                versionCode cdvVersionCode ?: defaultConfig.versionCode + 2  //this is the most case
                ndk {
                    abiFilters "armeabi-v7a", ""
                }
            }
            x86 {
                versionCode cdvVersionCode ?: defaultConfig.versionCode + 4
                ndk {
                    abiFilters "x86", ""
                }
            }
            all {
                ndk {
                    abiFilters "all", ""
                }
            }
        }
    } else if (!cdvVersionCode) {
      def minSdkVersion = cdvMinSdkVersion ?: privateHelpers.extractIntFromManifest("minSdkVersion")
      // Vary versionCode by the two most common API levels:
      // 14 is ICS, which is the lowest API level for many apps.
      // 20 is Lollipop, which is the lowest API level for the updatable system webview.
      if (minSdkVersion >= 20) {
        defaultConfig.versionCode += 9
      } else if (minSdkVersion >= 14) {
        defaultConfig.versionCode += 8   //Your "minSdkVersion" must be equal or larger than 14
      }
    }
```

In `platforms/android/AndroidManifest.xml`
You may have the line:
```xml
<uses-sdk android:minSdkVersion="14" android:targetSdkVersion="22" />
```

I created an new Cordova project and it passed my test :santa:

**Comment by garyganyang** [comment]
why does it have such a rule?

**Comment by tda7088** [comment]
Modify 8 in the end,it is ok,thanks very much

**Comment by vaenow** [comment]
@garyganyang I have explained [the rule 😃  ](https://github.com/vaenow/cordova-plugin-app-update/issues/3#issuecomment-199215000) above.

please let me know if you have any further questions.

**Comment by vaenow** [comment]
@tda7088 🔆

**Comment by Shepless** [comment]
@vaenow Sorry but I still do not understand the suffix of number `8` to the version? Also I do not understand why:

`12.234.221 === 1436218`

Can you explain to me please? I have read comment above but I still do not understand?

**Comment by vaenow** [comment]
Cordova official `version-code` rule:

https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#setting-the-version-code
