### ISSUE TITLE
请问version接受哪些格式？

### ISSUE THREAD

**Issue by formalin14** [vaenow/cordova-plugin-app-update#33]
只能是 324242 这样的吗？像 1.0.5 这样的可以吗？

**Comment by vaenow** [comment]
版本号都支持。

根据 [https://github.com/vaenow/cordova-plugin-app-update#versioncode](https://github.com/vaenow/cordova-plugin-app-update#versioncode)  
可知： 1.0.5 就转换为 10058 ，尾数 **8** 和Android版本有关系

所以保险起见，建议使用 
```js
var versionCode = AppVersion.build
console.log(versionCode) 
```
