### ISSUE TITLE
查詢下載 APK 後的貯存位置

### ISSUE THREAD

**Issue by prolog8** [vaenow/cordova-plugin-app-update#35]
如果在 Google Play Store 下載APP，預設存於共用的 Download 目錄(大家都能看見的)，而且沒有容量限制，只要手機空間足夠就行。

我們問題是：尊駕開發的 App Update (plugin) 啟動下載時，是否貯存於 APP 自身的目錄中(類似 file:///data/user/0/... ) ?

這代表着，APP下載後，用戶不能自行到共用的 Download 目錄手動安裝 APP (或取走那個 apk)。

Willow (上次忘記留名字)

**Comment by vaenow** [comment]
Hi Willow

Apk下载的位置的确是存储在外部存储卡里。参见代码：[https://github.com/vaenow/cordova-plugin-app-update/blob/master/src/android/DownloadApkThread.java#L41](https://github.com/vaenow/cordova-plugin-app-update/blob/master/src/android/DownloadApkThread.java#L41)

**Comment by vaenow** [comment]
I'm going to close this out, it's ok to reopen if the issue still exist.
