### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by hypBox** [vaenow/cordova-plugin-app-update#38]
Hi.

hope his email is correct and you have time to answer.
Great job on the plugin. Thank you

I have a problem with it, it checks the version and download the app correctly, but
after installation the app is just the old version before download. so it cause an infinite loop.

server version : 3.2.4
installed version : 0.3.2

could you please help?

**Comment by vaenow** [comment]
Please paste your `version.xml` 

and console out your version code 

```js
var versionCode = AppVersion.build
console.log(versionCode)  // 302048
```
