### ISSUE TITLE
Download of new version aborts instantly

### ISSUE THREAD

**Issue by Voakie** [vaenow/cordova-plugin-app-update#4]
I set up everything and now when I open my App, I get the notification that there is a new update. When I press `download`, the progress window opens but dissappears instantly afterwards. Any clues?

My version.xml on my server:
```
<update>
    <version>28</version>
    <name>DBG Vertretungsplan</name>
    <url>http://voakie.com/dbg/dl/android.apk</url>
</update>
```

Snippet from my index.js:
```
console.log("Version: "+AppVersion.build+" - "+AppVersion.version);
var updateUrl = "http://voakie.com/dbg/dl/version.xml";
window.AppUpdate.checkAppUpdate(onSuccess, onFail, updateUrl);
```

`onSuccess` and `onFail` are assigned. `onSucces` is always being called.
Thanks in advance!

**Comment by vaenow** [comment]
Thanks for your feedback.
> the progress window opens but dissappears instantly afterwards

Maybe you have an unstable network condition. 
I'm trying to open the link in chrome `http://voakie.com/dbg/dl/version.xml` and got `DNS_PROBE_FINISHED_BAD_CONFIG` occasionally.

**Comment by Voakie** [comment]
No matter where I open the site, it opens completely normal. I see the plain XML file...

See here:
http://image.prntscr.com/image/3b322d08f5ad4d468abec9a643dafcc8.png

**Comment by vaenow** [comment]
So, I just upload a demo apk. [cordova-plugin-app-update-demo](https://github.com/vaenow/cordova-plugin-app-update-demo) . Where you can type your own `updateURL` to fetch an update and check if it is work well.

see the screen shots.
