### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by cPerdereau** [vaenow/cordova-plugin-app-update#46]
Hello is it possible to change plugin language for French ?
I saw the XML but i dont wanna have to change the xml in node_modules!

**Comment by vaenow** [comment]
Maybe you should fork it and make your own language

referer: https://github.com/vaenow/cordova-plugin-app-update/issues/9

**Comment by cPerdereau** [comment]
Hello, thanks, can you warn me when its available after i created it, so i can try to npm update please?

:D thanks a lot

**Comment by vaenow** [comment]
@cPerdereau 

Language Fr has already been published on `npm`

**Comment by cPerdereau** [comment]
Great ! Thanks a lot :) :+1:

**Comment by cPerdereau** [comment]
Errmm..

How do you trigger the French language, it's still in English for me :s and Globalization tells me locale is FR.. :(

**Comment by vaenow** [comment]
refer:
https://github.com/vaenow/cordova-plugin-app-update/pull/10#issuecomment-245311705
> Android will ` automatic choose the language` depends on your phone setting.


Is there something I missed in the Fr pull request?

**Comment by cPerdereau** [comment]
Ok it seems to be working, i make a new request, i think you changed to 'google translate French' can you use my file please?

**Comment by cPerdereau** [comment]
`<?xml version='1.0' encoding='utf-8'?>
<resources>
    <string name="update_latest">Vous possédez la dernière version disponible!</string>
    <string name="update_title">Nouvelle Mise à Jour</string>
    <string name="update_message">Vous devez mettre l\'application à jour！</string>
    <string name="update_update_btn">Mise à Jour</string>
    <string name="updating">MàJ en cours</string>
    <string name="update_cancel">Annuler</string>
    <string name="update_bg">Mettre à jour en fond...</string>
    <string name="download_complete_title">Mise à jour terminée</string>
    <string name="download_complete_pos_btn">Re-télécharger</string>
    <string name="download_complete_neu_btn">Installer manuellement</string>

    <string name="update_error_title">Erreur</string>
    <string name="update_error_message">Connexion internet indisponible, merci de vérifier votre connexion.</string>
    <string name="update_error_yes_btn">OK</string>
</resources>`

**Comment by vaenow** [comment]
Oh! my fault!    i forgot a configuration in file [https://github.com/vaenow/cordova-plugin-app-update/blob/8bdf884358229e98c56bcfbc0fbad9364241bf95/plugin.xml#L42](https://github.com/vaenow/cordova-plugin-app-update/blob/8bdf884358229e98c56bcfbc0fbad9364241bf95/plugin.xml#L42)

**Comment by cPerdereau** [comment]
I think it's still the same, no values-fr :-/

**Comment by vaenow** [comment]
I dont have a PC now, I can only fix this issue tomorrow morning.

**Comment by cPerdereau** [comment]
It's ok! I'll wait don't worry ;) have a nice day !! thanks a lot :)

**Comment by vaenow** [comment]
@cPerdereau It seems working now. please have a try.

**Comment by cPerdereau** [comment]
Ok thanks, i'll try tomorrow morning ! thanks a lot :

**Comment by cPerdereau** [comment]
Hello ! ok it works now ! But can you update my XML plz ? cause it wasnt right

**Comment by vaenow** [comment]
The npm version already published. 🙂
