### ISSUE TITLE
Always getting success

### ISSUE THREAD

**Issue by pierrejochem** [vaenow/cordova-plugin-app-update#5]
I get allways a success. Even if I change the version in the version.xml file. Any clue or idea?

I changed version from 100008 to 200008 just for testing.

My js code is:

```javascript
var appUpdate = cordova.require('cordova-plugin-app-update.AppUpdate');
appUpdate.checkAppUpdate(function() { alert('Success'); }, function() { alert('Fail'); }, "http://xxx/updates/version.xml");
```

**Comment by vaenow** [comment]
I've fixed this issue in [this commit](https://github.com/vaenow/cordova-plugin-app-update/commit/1f51d036e8a004bfa9f62ea6eab965a5cce63837).


Thank you for your feedback. 👍

**Comment by pierrejochem** [comment]
Thank you. Will try it directly on monday :-) what do you think about an englisch Translation? I would do that part.

**Comment by vaenow** [comment]
Waiting for your PR😊
