### ISSUE TITLE
res/xml/provider_paths.xml conflicts with similarly named file in cordova-plugin-camera

### ISSUE THREAD

**Issue by loban** [vaenow/cordova-plugin-app-update#55]
**Problem**
Both cordova-plugin-app-update and cordova-plugin-camera attempt to put the file provider_paths.xml into platforms/android/res/xml folder, which causes an error.

**Solution**
Rename provider_paths.xml to appupdate_paths.xml

**Comment by vaenow** [comment]
Could you please send me a Pull Request? 🙂

**Comment by loban** [comment]
Sending one right away!
