### ISSUE TITLE
cordova build android    android.support.v4.content.FileProvider   

### ISSUE THREAD

**Issue by ttgzs** [vaenow/cordova-plugin-app-update#58]
D:\vsdemo\UpdateAppDemo\UpdateDemo\platforms\android\src\com\vaenow\appupdate\android\DownloadHandler.java:14: ����: ���
��android.support.v4.content������
import android.support.v4.content.FileProvider;
                                 ^
D:\vsdemo\UpdateAppDemo\UpdateDemo\platforms\android\src\com\vaenow\appupdate\android\GenericFileProvider.java:3: ����: ��
���android.support.v4.content������
import android.support.v4.content.FileProvider;
                                 ^
D:\vsdemo\UpdateAppDemo\UpdateDemo\platforms\android\src\com\vaenow\appupdate\android\GenericFileProvider.java:9: ����: �Ҳ
�������
public class GenericFileProvider extends FileProvider {
                                         ^
  ����: �� FileProvider
D:\vsdemo\UpdateAppDemo\UpdateDemo\platforms\android\src\com\vaenow\appupdate\android\DownloadHandler.java:96: ����: �Ҳ�
������
:compileDebugJavaWithJavac FAILED

BUILD FAILED

Total time: 18.571 secs
            Uri uri = FileProvider.getUriForFile(mContext, "com.vaenow.appupdate.android.provider", apkFile);
                      ^
  ����:   ���� FileProvider
  λ��: �� DownloadHandler
ע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
4 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: cmd: Command failed with exit code 1 Error output:
ע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
D:\vsdemo\UpdateAppDemo\UpdateDemo\platforms\android\src\com\vaenow\appupdate\android\DownloadHandler.java:14: ����: ���
��android.support.v4.content������
import android.support.v4.content.FileProvider;
                                 ^
D:\vsdemo\UpdateAppDemo\UpdateDemo\platforms\android\src\com\vaenow\appupdate\android\GenericFileProvider.java:3: ����: ��
���android.support.v4.content������
import android.support.v4.content.FileProvider;
                                 ^
D:\vsdemo\UpdateAppDemo\UpdateDemo\platforms\android\src\com\vaenow\appupdate\android\GenericFileProvider.java:9: ����: �Ҳ
�������
public class GenericFileProvider extends FileProvider {
                                         ^
  ����: �� FileProvider
D:\vsdemo\UpdateAppDemo\UpdateDemo\platforms\android\src\com\vaenow\appupdate\android\DownloadHandler.java:96: ����: �Ҳ�
������
            Uri uri = FileProvider.getUriForFile(mContext, "com.vaenow.appupdate.android.provider", apkFile);
                      ^
  ����:   ���� FileProvider
  λ��: �� DownloadHandler
ע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
4 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by ttgzs** [comment]
IThe issue has been resolved.
1.npm install --save cordova-plugin-android-support-v4
2.cordova plugin add cordova-plugin-android-support-v4
3.check plugin   ionic cordova plugin list
4.remove android platform 
5.cordova platform add android --nofetch
6.cordova build android 
BUILD SUCCESSFUL

**Comment by vaenow** [comment]
Ref: #17
