### ISSUE TITLE
界面文本更改后，编译发布没有更新

### ISSUE THREAD

**Issue by liuxf** [vaenow/cordova-plugin-app-update#6]
appupdate_strings.xml中的文案更改后，app重新编译发布，但是升级提示还是没变化！

**Comment by vaenow** [comment]
不好意思，你的问题描述不是太清楚。请尽量把操作步骤罗列出来，这样便于问题的排查 😸

**Comment by liuxf** [comment]
我想修改升级提示的默认文案，比如：

> 软件框架有更新啦！

但是我在appupdate_strings.xml的配置中修改了，app编译之后，升级提示没有变成我修改的文案。

**Comment by vaenow** [comment]
我自己试了一下，配置文件 `appupdate_strings.xml` 是对的，但是文件路径你可有误

Path:

`platforms/android/res/values/appupdate_strings.xml`

再试试 😸

**Comment by liuxf** [comment]
thanks，我配置的是插件的xml文件，难怪没反应=。=

**Comment by vaenow** [comment]
👍
