### ISSUE TITLE
About Plugin

### ISSUE THREAD

**Issue by MarwahTarek** [vaenow/cordova-plugin-app-update#63]
Hello! Excuse me I don't exactly understand what this plugin does, I wanted to know?
To see if it can help me solve my problem, I have a developed app that is going to be installed from play store which uses the kiosk mode plugin (a launcher app), and I'm asked by my supervisor to find a way to update its version from within the app like using a URL or something like that as it is a launcher app. Is it possible?

**Comment by vaenow** [comment]
In theory, this is possible, please refer to
[cordova-plugin-app-update-DEMO](https://github.com/vaenow/cordova-plugin-app-update-demo)
