### ISSUE TITLE
I get the error code 301 file resolve fail，but i can't find my error in my xml

### ISSUE THREAD

**Issue by DerekMar** [vaenow/cordova-plugin-app-update#64]
This is my xml path (http://www.derekmar.cn:8080/arcgisApp/Update/AppUpdateOwner.xml),. 
And this is my AndroidManifest.xml
![image](https://user-images.githubusercontent.com/20637828/32223518-9c4c6b36-be78-11e7-8aee-edc75751fd27.png)

**Comment by FredeHo** [comment]
Same here, even when using the same XML URL from the demo...

**Comment by LanceJenkinZA** [comment]
The problem is here
https://github.com/vaenow/cordova-plugin-app-update/blob/b18b1b9fc860a6a975d2a5121695d2fbccfd1253/src/android/CheckUpdateThread.java#L83

As a work around, you can pass the authentication options, with `authType` set to a blank string.

```
AppUpdate.checkAppUpdate(console.log, console.error, "https://www.example.com/version.xml", {authType: ""})
```

**Comment by vaenow** [comment]
@LanceJenkinZA 

Thank you so much for your solution

**Comment by vaenow** [comment]
npm package is already updated to `1.4.9`
