### ISSUE TITLE
Cannot read property 'checkAppUpdate' of undefined

### ISSUE THREAD

**Issue by pattnayakpratik93** [vaenow/cordova-plugin-app-update#69]
Hi,
I am using Ionic version 1 with angularJS.
My Code:-
I am reading the version from a XML file in my server and if there is any change in version then i am updating. that will come in later part of code, but can u please tell me what i am doing wrong?
```js
var updateUrl = "C:/Users/pratik_pattanayak/version.xml";
this.AppUpdate.checkAppUpdate(updateUrl).then(function (response){
     console.log(response);
})
```

**Comment by vaenow** [comment]
Please try 
```diff
+ window.AppUpdate.checkAppUpdate
- this.AppUpdate.checkAppUpdate
```

**Comment by pattnayakpratik93** [comment]
With window.AppUpdate.checkAppUpdate also getting same error.

**Comment by vaenow** [comment]
Please make sure you have correctly installed the plugin.

**Comment by pattnayakpratik93** [comment]
I can see cordova-plugin-app-update folder in my plugins folder. it has res, src, www,  LICENSE, package.json, plugin.xml, readme.md and syncfromdemo.sh

**Comment by pattnayakpratik93** [comment]
Can u also explain how to remove the plugin and add again?

**Comment by vaenow** [comment]
```js
cordova plugin remove xxxx.xxx.xxx
```

more cordova docs: [https://cordova.apache.org/](https://cordova.apache.org/)
