### ISSUE TITLE
碰到的问题

### ISSUE THREAD

**Issue by moleoo** [vaenow/cordova-plugin-app-update#7]
1、不管当前版本比XML<VERSION>中的是高还是低，都是出现软件更新提示。
```xml 
<update>
     <version>18</version> 
     <name>手机端</name> 
     <url>http://....apk/android-debug.apk</url> 
</update>
```

设17，设22都是这样，开始是10000，设1000和302048都一样，我只改了这里和index中的XML指向，不知道是其他地方还需要修改还是哪里出了问题。

2、在UpdateManager.java里有一个192.168.3.102？的链接是怎么回事，根本就是死链，这里是什么用途，需要修改吗？

**Comment by vaenow** [comment]
- 无论版本号是多少，都提示软件更新。此时可能是软件版本号有问题，你可以在控制台下查询 

 ```js
var versionCode = AppVersion.build
console.log(versionCode)  // 302048
```  
  [versionCode](https://github.com/vaenow/cordova-plugin-app-update#versioncode)

- 192.168.3.102 可以忽略这个链接。 这是我调试使用的，没有别的效果
