### ISSUE TITLE
Cannot automatic compare AppVersion

### ISSUE THREAD

**Issue by DerekMar** [vaenow/cordova-plugin-app-update#72]
![tim 20171208093004](https://user-images.githubusercontent.com/20637828/33746911-030dbc36-dbfb-11e7-9609-36f4018909be.png)

![tim 20171208094026](https://user-images.githubusercontent.com/20637828/33747077-de8785f8-dbfb-11e7-9fcb-c5f0d23a1c5e.png)

This is my app's version(3.2.4),and The server version is18(0.0.1).However, the plugins will still download the apk! The comparsion of app version do not work。

**Comment by vaenow** [comment]
Hi did you use the latest npm version ?

https://www.npmjs.com/package/cordova-plugin-app-update

**Comment by DerekMar** [comment]
@vaenow ，Sure，cordova-plugin-app-update@^1.4.12，I has tested it on different mobile.

**Comment by arthursp** [comment]
I saw the problem, as soon as the version is different from the server which serve the APK, it tried to download it even if it's an old version.

**Comment by wxingheng** [comment]
我使用        "cordova-plugin-app-update": "2.0.2",
最新的版本  遇到了同样的问题     永远都会重复的提示更新  即使我已经更新了   还是提醒我更新。
希望获得一些帮助，感谢
