### ISSUE TITLE
Problems with Android 6.0

### ISSUE THREAD

**Issue by letstessellate** [vaenow/cordova-plugin-app-update#82]
Hello,

First of all, lot of thanks for your work, it's nice ! 👍 

I use Ionic 3 and tested your plugin with the ionic native plugin AppUpdate : https://ionicframework.com/docs/native/app-update/

Problem is that it's not working... 

**More details below :** 
The new version is detected and the pop-up appears telling that an update is available. But when you click on the update button of the pop-up, the loading bar never fills in and nothing happens. I tried to log the problem, but there is no log. I just managed to log the Promise returned by the plugin : the code returned by the plugin is a 201 code.

I tried your demo to be sure that it was not due to my code or to Ionic. With your demo on my device, when you click in "Check app update", a pop-up appear and when you click on the button, the pop-up fades out but nothing happens... The APK is not updated.

The device used for these tests is an Archos 70 Oxygen tablet based on Android 6.0.

I saw a previous issue for the plugin with Android 6.0+ but that did not help.

Did someone have the same problem ? Do you know where it can come from ?

**Comment by letstessellate** [comment]
Sorry, Sorry and again Sorry, I made a stupid mistake in the APK link. You can remove my post ;)

**Comment by eduardolopesUFJF** [comment]
Hi there! I'm with exacty same problem. What did you do solve? I'm putting the same folder where I'm read the update.xml, but after select update, nothing happens. Thanks a lot!
