### ISSUE TITLE
Always getting "Network Error"

### ISSUE THREAD

**Issue by BrunaChamon** [vaenow/cordova-plugin-app-update#84]
The application always return error code 405. Links in xml is used in other application e no have problems open in browser, only in Ionic.  Can you help me? 

My ionic info prints:
    ionic/cli-plugin-proxy : 1.5.6
    ionic/cli-utils        : 1.19.0
    ionic (Ionic CLI)       : 3.19.0

local packages:
    ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

**Comment by BrunaChamon** [comment]
Change allow-intent in config.xml works for me. Sorry. hahaha

**Comment by luchillo17** [comment]
@brunachamon-hotmart How are we supposed to change the allow-intent to fix this error?
