### ISSUE TITLE
UPDATE the IONIC corresponding plugin

### ISSUE THREAD

**Issue by arthursp** [vaenow/cordova-plugin-app-update#86]
Hello, 

could you please update the corresponding IONIC native plugin to match parameters ?

**Comment by vaenow** [comment]
Hi @arthursp ,

I've found the source code about the native plugin. 
https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/app-update/index.ts

I'm not familiar with `ionic`. but don't worry, I will still fix the parameters asap.

**Comment by arthursp** [comment]
Hi @vaenow,
sorry I thought you were the author of the ionic plugin corresponding to your cordova plugin.
I allready fixed it on my project, the only thing to do is to add the auth parameter : 

checkAppUpdate(updateUrl: string, auth:any): Promise<any>;

**Comment by vaenow** [comment]
👍
