### ISSUE TITLE
Change language.

### ISSUE THREAD

**Issue by xutech** [vaenow/cordova-plugin-app-update#9]
Hello, thanks for this work ! How i can change the language without passing by Java (Just with config.xml or Js) ?

**Comment by brauchle** [comment]
Is the localization feature already implemented? I saw that you created the xml-files for the english translation, but how do i tell your plugin that i want english? Or is this just not finished?

**Comment by brauchle** [comment]
Just read the other issue with regarding language.
So its automatically used by the Android-Language - i am using a german tablet, but its using the chinese stuff. Would'nt it be more suitable to set the default language to english?

Would it be possible to give you the german translations?

**Comment by vaenow** [comment]
Sorry for reply you so late. 

@xutech you can change the display language through adding or modifying the [values-xml-files](https://github.com/vaenow/cordova-plugin-app-update/tree/master/res) 😄 

@brauchle I have `set the default language to English` if there are no translations available [see commit](https://github.com/vaenow/cordova-plugin-app-update/commit/8ec6214d844b53a49aaf27b9cb951efdeb177726)
